# Generated by Django 3.2.4 on 2021-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersEmora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('login', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('connected', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=120)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=130)),
                ('avatar', models.BinaryField()),
                ('identify', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Emora',
        ),
    ]
