# Generated by Django 3.2.4 on 2021-06-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0003_auto_20210626_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsemora',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='productsemora',
            name='connected',
        ),
        migrations.AlterField(
            model_name='productsemora',
            name='images',
            field=models.BinaryField(),
        ),
    ]
