# Generated by Django 3.2.4 on 2021-06-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0004_auto_20210626_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsemora',
            name='disponibilite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productsemora',
            name='priceUi',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
