# Generated by Django 3.2.4 on 2021-06-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0005_auto_20210627_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsemora',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='emora.usersemora'),
        ),
    ]
