# Generated by Django 3.2.4 on 2021-06-27 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0006_alter_productsemora_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsemora',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='emora.usersemora'),
        ),
    ]
