# Generated by Django 3.2.4 on 2021-06-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0007_alter_productsemora_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsemora',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner_id', to='emora.usersemora'),
        ),
        migrations.CreateModel(
            name='SaleOrderEmora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('disponibilite', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=120)),
                ('amount_total', models.DecimalField(decimal_places=3, max_digits=9)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order_id', to='emora.usersemora')),
                ('product_ids', models.ManyToManyField(blank=True, related_name='products_list', to='emora.ProductsEmora')),
            ],
        ),
    ]
