# Generated by Django 3.2.4 on 2021-06-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0008_auto_20210627_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEmora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('amount_total', models.DecimalField(decimal_places=3, max_digits=9)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner_cart_id', to='emora.usersemora')),
                ('product_ids', models.ManyToManyField(blank=True, related_name='products_list_cart', to='emora.ProductsEmora')),
            ],
        ),
    ]
