# Generated by Django 3.2.4 on 2021-06-27 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0009_purchaseemora'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseemora',
            name='purchase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchase_id', to='emora.usersemora'),
            preserve_default=False,
        ),
    ]
