# Generated by Django 3.2.4 on 2021-06-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0010_purchaseemora_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseemora',
            name='purchase_id',
        ),
    ]
