# Generated by Django 3.2.4 on 2021-06-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emora', '0011_remove_purchaseemora_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseemora',
            name='purchase_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_purchase_id', to='emora.usersemora'),
        ),
    ]
